### ISSUE TITLE
implicit declaration of function ‘read_cr4’

### ISSUE THREAD

**Issue by gokhalesushant65** [softdevteam/user_rdpmc#2]
After firing 'make', I am getting the following errors:
[make_error.txt](https://github.com/softdevteam/user_rdpmc/files/2879560/make_error.txt)

What should be done?

**Comment by ltratt** [comment]
I noticed this warning in the file you pasted:

```
Cannot use CONFIG_STACK_VALIDATION=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel
```

Can you install those packages and see if it fixes things?

**Comment by vext01** [comment]
It looks like read_cr4 was renamed recently(ish):
https://devtalk.nvidia.com/default/topic/813458/linux-4-0-rc1-346-47-build-error-_cr4-functions-fix/

After trying @ltratt's suggestion, can you try the renaming and let us know if it works (or better, raise a PR).

Thanks!

**Comment by gokhalesushant65** [comment]
Thanks @ltratt  and @vext01 
Renaming the function calls resolved the issue. Closing issue.
